### ISSUE TITLE
Use ArkDoc comments style for the standard library and builtins

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#114]
- [x] standard library
- [x] builtins

ArkDoc: https://github.com/ArkScript-lang/ArkDoc

**Comment by rakista112** [comment]
I'll help with this. But aren't the Builtins in C++ files?

**Comment by SuperFola** [comment]
That's the problem, we need arkdoc to be able to read documentation from c++ files

**Comment by rakista112** [comment]
Should this issue be filed in the ArkDoc repo?

**Comment by SuperFola** [comment]
Yes

Also we need to define a format for the ark/c++ documentation bridge, but I think we will settle on a doxygen like syntax
