### ISSUE TITLE
Function capture in arkscript

### ISSUE THREAD

**Issue by PierrePharel** [ArkScript-lang/Ark#134]
better arkscript function capture with function_view based on vitterio romeo function_view implementaiton

**Comment by SuperFola** [comment]
Our problem is that std::function uses 32 bytes

A function pointer uses 8 bytes but doesn't allow capture

**Comment by SuperFola** [comment]
Closing because our tests were not successful, and we moved away from `std::function`, now using `Value (*) (std::vector<Value>& args, Ark::VM* vm)`, with user data stored in the VM.
