### ISSUE TITLE
Check for unbound variables (during parsing or compile time)

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#144]

**Comment by owenl131** [comment]
```
(let fn (fun () (print z)))
(fn)  # unbound variable
(let z 1)
(fn)  # no unbound variable
```
Currently the scoping rules cause there to be no way to definitely say if a variable is unbound without actually executing the code. We could do two passes over the AST, first to collect all the symbols and later to check if any of the symbols are used but not defined.

**Comment by SuperFola** [comment]
That is possible actually, the optimizer is already doing this kind of thing (counting variables occurences and stuff), we could easily add that
