### ISSUE TITLE
Enhance module interface to make it C compatible

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#156]

**Comment by PierrePharel** [comment]
The main problem is module's functions mapping...i guess
That can only made with C++. And perhaps add an C's container to manipulate Ark objects.

**Comment by SuperFola** [comment]
My idea is to ditch the current Mapping_t (unordered map of string to values) and rely on something more like `mapping*`, with

```c
struct mapping {
    char *name;
    Value (*function) (std::vector<Value>&, Ark::VM*);
};
```

**Comment by SuperFola** [comment]
The CI just broke, and on my computer too. Most likely an update in MSVC now forbidding C functions to return C++ classes
