### ISSUE TITLE
Add more arguments/options to the bytecode reader to select code segments

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#158]
The idea would be to be able to select a specifc code segment given its PP (page pointer), also to slice a code segment (some can be as long as 2000 instructions, it could be great to say "hey I want the code segment 12, from instruction n°144 to instruction n°244".

Could also be great to be able to slice the constants table/symbols table and also to print only the constants table/symbols table.

Needed files are located in include/Ark/Compiler/BytecodeReader.hpp and src/Compiler/BytecodeReader.cpp

**Comment by krgulshan007** [comment]
Constable

**Comment by JSanestrzik** [comment]
Hi, i would like to pick up this issue. 

What should happen if i select a code segment or table and i provide a range of instruction that is longer then the segment/table?

**Comment by SuperFola** [comment]
Hi there!

Then, nothing (in term of instructions) should be displayed (check size first), but an error / warning could be added to specify the size of the segment/table

**Comment by JSanestrzik** [comment]
Had a busy last week, I just started working on this and some additional questions came to my mind.

Should the slicing of the value/symbol table and code pages be only applicable to the printing of the human readable byte code? or should it also be able to deliver the bytecode itself as a slice?

**Comment by SuperFola** [comment]
IMHO it should only be applied to the human readable byte code (eg if we ask for bytes 23 to 53, if byte 23 is an argument of an instruction, this instruction should be displayed, same goes for 53), otherwise we would be reading nonsense if we took byte 23 to 53 and byte 23 wasn't a known instruction but a random number serving as the argument of another instruction

**Comment by SuperFola** [comment]
Hi there!

I wanted to check on you to known if you're still interested in working on this, otherwise I will reassign this issue

**Comment by JSanestrzik** [comment]
Hi, I'm still interested. Sorry for the delay in the last couple of weeks were quite busy for me. 
I wasn't happy with the solution I came up with so I rewrote it a couple of times already. But I think the current one is good enough so I will take another look at it and prepare a PR soon.

**Comment by SuperFola** [comment]
No problem, I totally understand

Looking forward to your PR then

**Comment by JSanestrzik** [comment]
Sorry for the delay I think i kinda figured how this endless Wednesday works... or at least I'm on the right track. I was thinking about refactoring the display method because clang tidy was crying about the complexity. I was never happy with the result. So i decided to alter the existing function by adding additional method parameters and configuring the display accordingly.

**Comment by SuperFola** [comment]
Sounds good to me!

**Comment by SuperFola** [comment]
Closing since #219 is working and merged, setting the arguments for the `display` method of the bytecode reader can be redirected in another issue
