### ISSUE TITLE
Wrong line number displayed/used when code is wrong in the parser

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#159]
In the tests I wrote `(let r (range (0 10)))` instead of `(let r (range 0 10))` and the parser mistakenly reported an error on line 3 of the file (at the first `"` in `(import "Range.ark")`), thus we can assume it's because either of an error on the lexer side or on the error reporter code from the parser

**Comment by snehal199** [comment]
Hey @SuperFola, I would like to try this out. Could you elaborate on what is it that needs to be done? A newcomer here!

**Comment by SuperFola** [comment]
Hey @snehal199 , no problem!

As far as I can tell for now, the problem should be located under
- src/Compiler/Lexer.cpp
- include/Ark/Compiler/Lexer.hpp
- include/Ark/Compiler/Lexer.inl

and maybe under
- src/Compiler/Parser.cpp
- include/Ark/Compiler/Parser.hpp
- include/Ark/Compiler/Parser.inl
as well.

From a few glance at this bug (I tried multiple situation (putting a comment / a correct declaration / a correct import statement before the problematic line)), it appears that the line number given to every token (especially the ones for `()[]{}`) are sometimes equal to 1 instead of the current line.

Maybe I'm wrong, but it appears that it would be a small fix when lexing (checking that the line number given is correct, and that's it's unmodified later in the parser).

Note that the parser can add new tokens without checking the line number (thus putting 1 as the line number) (but afaik it *shouldn't* be the problem here).

------

The minimum code needed for reproduction is something like this:
```clojure
# whatever under this line will be reported as the problem while it isn't
(let b 12)
# the real problem is here
(let a (12))
```

**Comment by Saul-BT** [comment]
Let me try to solve this

**Comment by owenl131** [comment]
Hi, I have submitted a fix, explanation is within the PR. Looking forward to hearing for your feedback!
