### ISSUE TITLE
Create a smaller variant

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#167]
We are losting 8 bytes for nothing with std::variant, thus `Value_t` is about 32 bytes, and Value is 40 bytes (32 + 1 bytes + alignment)

**Comment by PierrePharel** [comment]
Small ?

**Comment by SuperFola** [comment]
Linked to #168, now using mpark variant (cf PR #211), we are faster than with the STL variant (gained a few seconds on heavy benchmarks)
