### ISSUE TITLE
Memory leak when ARKSCRIPT_PATH is empty and we're searching for files to include

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#189]
Seems like we enter an infinite loop trying to retrieve a file it can't find, thus eating too much memory and ending up killing the process

**Comment by PierrePharel** [comment]
Hmm...I have an idea for fix. But It can be weird....

**Comment by SuperFola** [comment]
Most likely linked to the fact the when I do a `getenv("ARKSCRIPT_PATH")` it's empty and I don't check the value, must be located in the State and also in the parser when running the recursive import detector. The memory leak is from the import detection, but that must be caused by the State not loading the right value for `ARKSCRIPT_PATH`

**Comment by SuperFola** [comment]
Can't replicate for now, though it's a good reminder that we should rewrite the parser

**Comment by SuperFola** [comment]
Seems to be fixed thanks to the new update of the State and Parser
