### ISSUE TITLE
Add chr(integer) and ord(character) like functions

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#191]
To create characters from char code and to get char codes from characters

**Comment by fizzyjosh555** [comment]
Hey, I was wondering if I could do this? If so, where would I write the functions?

**Comment by SuperFola** [comment]
While thinking about it, i came up with a few problems before we can add those: the lexer doesn't handle utf8 strings correctly, and our internal string doesn't handle them neither.

Otherwise it would have to be C++ builtins, under include/Ark/Builtins/ and source/Builtins/String.cpp

I shall write a short guide on how to add builtins soon
