### ISSUE TITLE
fix CI - add openssl when needed

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#223]
Docker CI and MacOS don't pass because they can't find OpenSSL

**Comment by SuperFola** [comment]
May be related to the modules repository but since the CI is running from here, I don't really know.

**Comment by SuperFola** [comment]
CI fixed, added back the `-DARK_BUILD_MODULES` and added flags to turn on/off specific modules, ping @PierrePharel , you will like to hear that I think :D

**Comment by PierrePharel** [comment]
oh yeah
