### ISSUE TITLE
Builtins and std lib modules

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#23]
This issue will be used to keep track of the needed builtins and std lib functionnalities for the 3.1.0

## List

- [x] `(zip list1 list2)`
- [x] `(map func list1)`
- [x] sorting algorithms
- [x] reverse array
- [x] find object in array
- [x] delete element at index and return new list
- [x] `(slice array from_index to_index step)`
- [x] implement forEach (already done in examples/for-each.ark, but it can be greatly improved)

## Dictionnary

- [x] ~~dictionnary implementation using closures~~ see the json module

## String

- [ ] regexes
- [x] reverse string
- [x] find substring in string
- [x] `(slice string from_index to_index step)`
- [x] `(removeAtStr string index)`

## Network

- [ ] create socket
    - [ ] TCP/IP
    - [ ] UDP
- [ ] close socket
- [ ] send data
- [ ] receive data
- [ ] make ARP request
- [ ] make ICMP packets

## Mathematics

- [x] trigonometrics
    - [x] cos, arccos
    - [x] sin, arcsin
    - [x] tan, arctan
- [x] exp, log
- [x] pow (can be implemented in ArkScript with `exp` and `log`)
- [x] sqrt (can be implemented in ArkScript with `pow`)
- [x] ceil, floor, round
- [x] sum (elements from list)
- [x] is infinite, is nan
- [x] pi, e, tau, inf, nan

## ~~SFML~~
- [x] ~~Graphics~~
- [ ] ~~Audio~~
- [ ] ~~Window~~
- [ ] ~~System~~
- [ ] ~~Network~~

Not part of the standard library anymore, was moved to https://github.com/SuperFola/arksfml

**Comment by Natendrtfm** [comment]
createFile method ?
(createFile "filepath/filename" "file default content") for example
NB: ad an assert for see if the file alreadyexist

**Comment by SuperFola** [comment]
writeFile with mode set as w already does that 😉

**Comment by SuperFola** [comment]
Added Network to the needed modules (see the original post)

**Comment by Natendrtfm** [comment]
- [ ] Add math functions

**Comment by SuperFola** [comment]
Adding it now to the todo list

**Comment by SuperFola** [comment]
I think we'll need to discuss the naming convention (which should be shared by modules and scripts from the standard library) soon, as well as the organization of the lib/ folder.

Maybe it would be better to have something like
```
lib/
    String/
        Case.ark
        Reverse.ark
        Slice.ark
        ...
    Math/
        ...
    Functional/
        Either.ark
        Compose.ark
        ...
    List/
        Reverse.ark
        Slice.ark
        ...
    String.ark  # importing all files from String/
    Math.ark    # importing all files from Math/
    ...
```

and name the functions as following `module(-submodule(-...))-function`

What are your opinions about that?

**Comment by Natendrtfm** [comment]
Add a element at the beggining of a list

**Comment by Natendrtfm** [comment]
Playing sounds

**Comment by SuperFola** [comment]
very soon with the SFML module, we'll be able to do that!

**Comment by SuperFola** [comment]
As stated in https://github.com/SuperFola/Ark/issues/23#issuecomment-540174469, I decided to put string related files in lib/String, same for math, functional... but not rename the functions.

The camelCase will be used for the functions of the standard library, and if there can be a conflict, a suffix will be added. Example: reverseStr and reverseList.

For the modules written in C++, the camelCase will be used as well. When interfacing `sf::Window::Graphics::RenderWindow` for example, it will be named `sfWindowGraphicsRenderWindow`.

The modules will stay in ./lib/ for the moment, until we have more of them.

**Comment by SuperFola** [comment]
Added maths functions and constants, `findSubStr`, `zip` and `map` in commits 3d82bbdc..bea97710

**Comment by rinz13r** [comment]
What are the expected semantics of the array builtins? Do the following sound okay?

1. Find:
- param: list, index (Number).
- return: Value at that index.
- misc: If the index is out of bounds, a TypeError is thrown.

2. Delete:
- param: list ref, index (Number).
- return: modified (value at that index removed) list ref.
- misc: If the index is out of bounds, a TypeError is thrown.

3. Slice:
- param: list ref, start index (Number), end index (Number), step (Number)
- return: A new list instance containing elements of the input list b/w indices start and end spaced by step.

Any pointers on sorting heterogeneous lists would be highly appreciated.

**Comment by SuperFola** [comment]
About find, you're describing `(@ list index)` actually ; find should look into a list for a specific Value. If Value can't be found, better throwing a std::runtime_error. Still unsure on how to name this function, since we have `findSubStr` to search for a substring in a given string, I'm open to any idea.

About delete, it would be better to throw a std::runtime_error if the index is out of bound, otherwise it looks good to me. I think it should be named removeAt, what do you think?

About slice, it should be named sliceList (we already have sliceStr) but otherwise it looks good to me!

**Comment by rinz13r** [comment]
> About find, you're describing (@ list index) actually ; find should look into a list for a specific Value. If Value can't be found, better throwing a std::runtime_error. Still unsure on how to name this function, since we have findSubStr to search for a substring in a given string, I'm open to any idea.

Oh, Gee. Apologies for the blunder. Throwing an std::runtime_error sounds good. Maybe the name can be findList?

> I think we'll have to define a semantic for ordering values (should a < b, with type(a) != type(b) always be false? or maybe first put the numbers, then the strings, etc?) in another issue.

What you suggest sounds good and can be implemented easily. I think JS follows a similar approach.

> I think it should be named removeAt, what do you think?

For the naming of functions, maybe we can follow verb+ClassName? So in this case it becomes removeAtList. What do you think?

**Comment by SuperFola** [comment]
> Maybe the name can be findList?

This suggests that we are search for a list, maybe `findInList`? Or we could go with a `indexOfInList` but that's a bit too long IMHO.

> What you suggest sounds good and can be implemented easily. I think JS follows a similar approach.

I'll work on that ASAP then, I think we'll just have `a < b` returning false if type(a) is lower than type(b) in ValueType (List, Number, String, PageAddr, NFT, CProc, Closure).

> So in this case it becomes removeAtList. What do you think?

Sounds good to me, and it rang a bell: we should as well have a `removeAtStr`.

**Comment by PierrePharel** [comment]
I will work on implementation of dictionnary, based on Ruby's hash (https://devdocs.io/ruby~2.6/hash)

**Comment by SuperFola** [comment]
I'm pondering the necessity of having network builtins in the language.

That would rather be an external module (may it be standard or not) in my opinion, thus we could close this issue, unless someone thinks otherwise (i.e. the builtins set is not wide enough to work on the standard library only from now on).

What do you people think?
