### ISSUE TITLE
Syntax error when compiling macro from cli tool

### ISSUE THREAD

**Issue by rakista112** [ArkScript-lang/Ark#240]
**Describe the bug**
The CLI tool raises a SyntaxError when compiling a script with a macro copy pasted from the tutorial

**To Reproduce**
1. Download the Winx64 release from [Github](https://github.com/ArkScript-lang/Ark/releases/tag/v3.0.15)

**Expected behavior**
The compiler should compile the script with the macro into bytecode.

**Code or Screenshots**
![image](https://user-images.githubusercontent.com/815354/114973452-185cc680-9eb3-11eb-891f-3f7bade38d1f.png)

**ArkScript version or commit hash**
Version 3.0.15

**Additional context**
I'm running on Windows 10. I tried running ark.exe -c on the scripts in Powershell and cmd and it still gives me the SyntaxError.

**Comment by SuperFola** [comment]
Hi, thanks your interest in the language

The macros aren't published yet (in a release) thus the old releases don't know them. We are aiming to release them this month if everything goes right!

You can still try them by compiling the project, but I can also provide demo binaries I guess!
