### ISSUE TITLE
Refactor our cmake configs

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#254]
Currently, our cmake configs are quite bad.

Ark's CMakeLists.txt is more than 200 lines, doing heavy things, abusing mecanisms like include_directories instead of target_include_directories, which is (AFAIK) non-idiomatic CMake.

Also I solved a problem where compilation flags weren't synchronized between projects (ArkScript and our modules) but it uses global properties and I'm guessing that it's quite bad.

We could refactor the cmake configs to have one per directory and use `target_sources` and `source_groups` (see https://github.com/GentenStudios/Phoenix/, it's using this practice, allowing easy development in VS by showing the source groups correctly)

**Comment by PierrePharel** [comment]
VS mean ?

**Comment by SuperFola** [comment]
Visual Studio, the IDE

**Comment by PierrePharel** [comment]
why this preference for VS ?

**Comment by SuperFola** [comment]
If this problem arise in this IDE, it will arise with other IDE. Also so VS is the best IDE on Windows

**Comment by PierrePharel** [comment]
VS is the best or the more pratice on windows

**Comment by PierrePharel** [comment]
And a preference of an IDE in compilation config is not a good idea for me

**Comment by SuperFola** [comment]
You didn't understand my point, it isn't about forcing an IDE, just using idiomatic CMake which will as well solve problems on VS and many other IDE working the same way!

**Comment by PierrePharel** [comment]
No, I understand, but the allusion  of VS, is not necessary 😅

**Comment by SuperFola** [comment]
Well it is to explain why using source groups and stuff is interesting, otherwise we "could" stay with the old model :)
