### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#260]
We never have enough tests (may they be in ArkScript or C++).

We need to have more tests, to ensure every language construct continue to work properly, and that our C++/ArkScript integration is working properly.

**Comment by gautamV19** [comment]
I am interested in working on this issue. Can you just guide me how should I start?

**Comment by SuperFola** [comment]
Sure!

1. You will probably want to see if you can build the project correctly before starting, we have a guide at https://arkscript-lang.dev/tutorials/building.html#from-source
2. Then you will probably want to get familiar with the language and/or the API (https://arkscript-lang.dev/impl/ and https://arkscript-lang.dev/tutorials/language.html)
3. All the tests are in tests/, we have different directories for:
  1. the tests written in ArkScript itself,
  2. in C++ to test the integration of ArkScript (running code in the VM, instanciated in c++, getting values from C++, adding functions in C++ to the VM, etc)
  3. The AST, which can be obtained as plain JSON (this ensure that the lexer, parser, macro processor and optimizer are doing their job correctly)

The goal of this issue is somewhat linked to #328: we lack test coverage, currently on the builtins (in ArkScript itself), on the C++ integration and on error behaviours as stated in #328 (checking that we are actually detecting errors for a given code, either in the lexer, parser, macro processor, compiler or VM).

If you have questions along the way, feel free to ask.

**Comment by SuperFola** [comment]
Currently adding more tests while fixing as many bugs as possible reported by the fuzzers. Once this is done in about a month (if I can keep it up) we should have a strong basis for tests (errors are being thoroughly tested (compiler and runtime), as well as components (like the bytecode reader) via boost::ut).
