### ISSUE TITLE
Parser bug with keywords in the middle of blocks

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#276]
**Describe the bug**
Keywords seem to be allowed in the middle of blocks.

**To Reproduce**
1. Write `(let check (fun (callback) (= fun (type callback)))) (print (check 1))`
2. Run it
3. Observe no parsing nor compile time error

**Expected behavior**
A parser error telling the user they put a keyword where it wasn't meant to be.

**Code or Screenshots**
```lisp
(let check (fun (callback)
    (= fun (type callback))))

(print (check 1))
```

**ArkScript version or commit hash**
3.0.15

**Comment by Shehab7osny** [comment]
Hi @SuperFola
Can you please provide me with an easier example to reproduce this logical error?
I mean, an example with a simpler logic that could be easily used for debugging.

Thanks!

**Comment by SuperFola** [comment]
Hi!

The global problem is that, when running said example in the REPL, we don't get any error at all, and `(print (check 1))` displays false. However when running the sample from a file, like this `arkscript file.ark` (in Debug) we get an access error (`front() was called on an empty list`), most likely because the parser found the keyword `fun` and tried to parse the rest as a function definition.

This all ties down to having a keyword in the middle of an expression (even though I thought the tests in the parser were enough), like: `(print fun 12)` or `(+ 15 if 4)`. Keywords can not be anywhere else than right after an opening paren, otherwise this should generate an error.

Not the same error as the provided example, but small example: `(print (+ 1 fun 4))`, this generate a `TypeError: Arguments of + should have the same type` at runtime, and the generated bytecode is
```cpp
0 LOAD_CONST (Number) 1.000000
3 BUILTIN nil
6 ADD
7 LOAD_CONST (Number) 4.000000
10 ADD
11 BUILTIN print
14 CALL (1)
17 HALT
```
meaning that, somehow, the parser translated the `fun` to a `nil`.

I hope that it's clear enough, if not do not hesitate to ask.

**Comment by Shehab7osny** [comment]
So, just to make sure I got everything right,

Let's for example take the command of Printing 1 PLUS 2.

In a normal case we would do the following:
`(print (+ 1 2)`
This would result in an output of `3`

However if **fun** keyword is placed in between 1 and 2 in the expression the parser translates **fun** keyword to **nil** and this causes either incorrect output or incorrect error message.

Please let me know if I got anything wrong. If not, what is the expected error message to be printed in case the parser translates the **fun** keyword correctly?

**Comment by SuperFola** [comment]
This is correct. I would add that the problem can arise with any of the 10 keywords: let, mut, set, del, if, while, fun, begin, import, quote (can be checked via `if (node.nodeType() == NodeType::Keyword)`), not only with `fun`.

The expected error message would be along the lines of "unexpected keyword `{name}' in the middle of an expression".
