### ISSUE TITLE
Add repl dedicated features

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#278]
- [x] (repl:toFile filename) to store the expressions (+ results in comments) in a given file
- [x] (repl:reset) to reset the VM state and start from something fresh
- [x] consider key bindings

**Comment by henriquenunez** [comment]
Hello! I'm interested in this issue.

> (repl:toFile filename) to store the expressions (+ results in comments) in a given file
This should store the expression written so far in the runtime, quite like a log? Should there be any special formatting for the expressions and the results, so a further parsing is able to be done?

> consider key bindings
What kind of key bindings should be implemented?
