### ISSUE TITLE
Better error messages for builtins / modules functions

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#308]
It would be great to generate coherent and consistent error messages, following something like
1. `functionName: argumentName must be of type typeName.`
1.
```
functionName: needs argumentCount argument(s), got actualArgumentCount.
  -> arg1Name (wanted type) was arg1Value (of type arg1Type)
  -> arg2Name (wanted type) was arg2Value (of type arg2Type)
     [nota: this could be color coded to tell if the constraint was satisfied or not]
```

**Comment by madstk1** [comment]
I can do some work on this. Depending on how fancy it needs to be, you can make something that's very concise:
```cpp
(new SyntaxError())
    ->append("functionName: needs argumentCount argument(s), got actualArgumentCount.")
    ->append("  -> arg2Name (wanted type) was arg2Value (of type arg2Type)") // without args
    ->append("  -> ", val1, " (", val2, ") was ", val3, " (of type ", val4, ")") // with args
    ->eject();
```

**Comment by madstk1** [comment]
The only reason for the template is to simplify the `std::cout` call.

By the way, either I'm not competent enough in C++ or something, but when you say "would return a BetterTypeError& so that we can throw it directly," what do you mean?
