### ISSUE TITLE
Add binary/bool op

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#31]
- [x] rshift
- [x] lshift
- [x] binary or
- [x] binary and
- [ ] binary not `~`
- [x] not

**Comment by rinz13r** [comment]
In the Value structure, you are storing the data in an std::variant<double, std::string, size_t>.
So, any numeric value is stored finally as a double. The listed binary operations, however, work on integer types (int, long, etc.) and not the double type.

**Comment by SuperFola** [comment]
You're right, thanks for pointing it out. I'm now wondering if can afford to have a *double* number type (long vs double), and if we do, is that really useful?

At least we can implement `not` for booleans.

**Comment by rinz13r** [comment]
Or the crudest way is to round the number and apply the operator on it.

**Comment by SuperFola** [comment]
That's also a possibility, maybe we should vote?

If you don't think that rshift, lshift, binary or/and/not are needed, meaning that only `not` (for booleans) is needed, vote with 👍 

If you think rshift, lshift, binary or/and/not are needed, and thus a rough conversion double -> long is needed, vote with 👎

**Comment by rakista112** [comment]
We could make bitstrings in the std library just like MIT Scheme does it.
Instead dealing with converting to integers, we could 
* make a way to create bitstring like (make-bitstring "bitstring")
* make Ark method wrappers for bit manipulation
* and let c++ handle with std::bitset or our own implementation

**Comment by SuperFola** [comment]
I like the idea, however the standard library (in ArkScript) won't be very efficient for this, thus I would suggest to go with a standard module (in C++, with a UserType), generated from a string as you said

**Comment by SuperFola** [comment]
Implemented in ArkScript-lang/modules#39
