### ISSUE TITLE
Investigate why MacOS builds fail sometimes

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#320]
It seems like that half the time, the MacOS builds of ArkScript are failing and triggering segmentation faults. Relaunching the jobs "fixes" the problem somehow.

Alas I don't have a Mac to investigate this problem.

Something important to note (IMO): the MacOS CI is using Clang 12, but the Ubuntu CI are only going as far as Clang 11. Could it be a problem with Clang 12? Also, the Clang builds on Ubuntu never fail to run (I have tested them and debugged them, as I am running both Linux and Windows).

**Comment by rakista112** [comment]
I can test this on my Mac

**Comment by Loki-Astari** [comment]
Just added a pull request to fix some compiler warnings on mac.
https://github.com/ArkScript-lang/Ark/pull/329

Maybe this will help.

**Comment by SuperFola** [comment]
@rakista112 could you check and report if arkscript is still crashing on MacOS on the string tests?

**Comment by SuperFola** [comment]
According to the CI logs (and to my own Mac), ArkScript builds correctly now.
