### ISSUE TITLE
[InnoSetup] Find a way to change the AppVersion according to the current ArkScript version.

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#330]
Find a way to change the AppVersion (https://github.com/ArkScript-lang/Ark/pull/327/files#diff-f30851867bf10e050f01ebecb7a55cad0db52d49042f0f896d3be24e294575a4R3) according to the current ArkScript version.

_Originally posted by @SuperFola in https://github.com/ArkScript-lang/Ark/issues/327#issuecomment-943076975_

**Comment by madstk1** [comment]
Why not do it the other way around? Make an `Installer.iss.in` and configure it? Otherwise, we'd have to parse the .iss file with `file(STRINGS ...)` or otherwise.

**Comment by SuperFola** [comment]
This would actually work, quite easily since we don't need to build ArkScript, just setup cmake. Other solutions would be harder to use I guess (like running CMake to build ArkScript, then running Python/Ruby/JS/whatever to parse and update the InnoSetupScript, then running ISCC to build the installer?)
