### ISSUE TITLE
REPL: can't import plugin and use it

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#337]
**Describe the bug**
It seems like when we import a plugin in the REPL and then try to run one of its function, it's deleted before running the function.

**To Reproduce**
1. Compile arkscript and the console module
2. Run `build/arkscript`
3. Type `(import "console.arkm")` in the REPL, then hit enter ; type `(console:clear)` and hit enter

**Expected behavior**
The functions of the imported modules should stay imported.

**Code or Screenshots**
![image](https://user-images.githubusercontent.com/10694085/137595442-fc764c59-c270-4fed-8e86-ac2c7f730d04.png)

**ArkScript version or commit hash**
3.1.1

**Comment by Loki-Astari** [comment]
Seems like there is a missing step in the instructions.

````
> build/arkscript
ArkScript REPL -- Version 3.1.2 [LICENSE: Mozilla Public License 2.0]
Type "(quit)" to quit.
main:001> (import "console.arkm")
Could not find module 'console.arkm'. Searched in
	- console.arkm
	- lib
At IP: 2, PP: 0, SP: 0
````

Is there an environment variable I should set to point it where to find console.
