### ISSUE TITLE
Broken MemCopy

### ISSUE THREAD

**Issue by Loki-Astari** [ArkScript-lang/Ark#340]
**Describe the bug**

There is a memcopy that is very broken:

````
/home/runner/work/Ark/Ark/lib/modules/submodules/msgpack-cpp/include/msgpack/object.hpp:617:34: error: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘struct msgpack::v1::object’ from an array of ‘const msgpack_object’ {aka ‘const struct msgpack_object’} [-Werror=class-memaccess]
  617 |     std::memcpy(&o, &v, sizeof(v));
````

The src type is `struct msgpack_object`
is defined in: lib/modules/submodules/msgpack-cpp/include/msgpack/object.h as 

````
 88 typedef struct msgpack_object {
 89     msgpack_object_type type;
 90     msgpack_object_union via;
 91 } msgpack_object;
````

This is  being copied into: `struct msgpack::v1::object’
is defined in: lib/modules/submodules/msgpack-cpp/include/msgpack/object_fwd.hpp

````
106 struct object {
107     union union_type {
108         bool boolean;
109         uint64_t u64;
110         int64_t  i64;
111 #if defined(MSGPACK_USE_LEGACY_NAME_AS_FLOAT)
112         double   dec; // obsolete
113 #endif // MSGPACK_USE_LEGACY_NAME_AS_FLOAT
114         double   f64;
115         msgpack::object_array array;
116         msgpack::object_map map;
117         msgpack::object_str str;
118         msgpack::object_bin bin;
119         msgpack::object_ext ext;
120     };
121
122     msgpack::type::object_type type;
123     union_type via;
````

There are no guarantees that the layout of these objects is the same (especially since the first is a C struct and wrapped inside `extern "C"` declaration and the other is a C++ class (yes a C++ struct is the same as C++ class).

There is also a maintenance issue that `msgpack::type::object_type` and `msgpack_object_type` must be kept in sync, but there is no validation to see if there is a change in either.

**To Reproduce**
Compile on Linux with GCC and set the warning flag: -Werror=class-memaccess
 
**Expected behavior**
Compile with no error.

**Comment by Loki-Astari** [comment]
I can look at this.
If somebody can assign me.
Thanks

**Comment by SuperFola** [comment]
Wow, thanks for looking into this, I didn't even know we had such code

**Comment by Loki-Astari** [comment]
https://github.com/ArkScript-lang/msgpack-cpp/pull/1

**Comment by SuperFola** [comment]
Closing as the linked PR was merged.
