### ISSUE TITLE
Can we avoid building ArkScript 2 times in the CI?

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#351]
Currently, for every target (OS and compiler), ArkScript is being built 2 times: to run the language tests, and to run the integration tests.

It would save a lot of time if we could build ArkScript only once, and reuse it for the integration tests.

**Comment by rakista112** [comment]
Is there a way to store the binaries on the agent?
I wonder if there's agent/machine/job local persistence.

**Comment by rakista112** [comment]
Here it is https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
Theoretically, we "upload" the Arkscript binary in the OS/compiler target, then download in another job to test

**Comment by SuperFola** [comment]
Also since it's in the same job we can reuse what has already been compiled.

The only burden is that we have two different cmake projects, so reusing the compiled arkreactor can be difficult.

**Comment by SuperFola** [comment]
Bad idea but hear me out:

- do not `add_subdirectory(.. ark)` in the tests CMakeLists
- add `include_directories(../include)` in the tests CMakeLists
- link against `../build/$<CONFIG>/libArkReactor.${the right extension here}` in the tests CMakeLists
