### ISSUE TITLE
I'm a little confused.

### ISSUE THREAD

**Issue by eboatwright** [ArkScript-lang/Ark#376]
So, hi! Hello! This looked very interesting, and I've been looking for a new programming language for my game dev, and I was wondering... So, the description says "A scripting language for C++ projects". Does that mean that it's like Lua, where you have to put it into your own C++ project, or can it compile, and build as a programming language?

**Comment by SuperFola** [comment]
Hi!

ArkScript is a language on its own, with a focus on easy embedding in C++ projects. In a way it's like Lua, you can use it on its own (see [how to build ArkScript](https://arkscript-lang.dev/tutorials/building.html#from-source)), or embed it in your games (see [how to embed ArkScript](https://arkscript-lang.dev/impl/d7/dea/tutorial_embedding.html)).

**Comment by eboatwright** [comment]
Oh and what about cross compiling? Can you cross from Linux to Windows? :D

**Comment by rakista112** [comment]
@eboatwright I haven't tried it but you could try cross compiling with the right platform packages installed http://www.swarminglogic.com/article/2014_11_crosscompile
You might encounter a couple of problems (hidden dependencies, directive conflicts) but it's worth trying out.

**Comment by eboatwright** [comment]
Cool! Thanks
