### ISSUE TITLE
VM shows invalid instruction on ARMv7

### ISSUE THREAD

**Issue by hardliner66** [ArkScript-lang/Ark#426]
### What happened?

I tried to cross-compile arkscript with yocto to an ARMv7 platform, but when I run it, it can only execute the first command properly. After that, the VM is in a weird state.

### What ArkScript version are you seeing the problem on?

v4.0.0-0.1

### Relevant code & log output

```shell
root@imx6sx-pilot:~# arkscript 
ArkScript REPL -- Version 4.0.0 [LICENSE: Mozilla Public License 2.0]
Type "(quit)" to quit.
main:001> (+ 1 2)
main:002> 
unknown instruction: 0
At IP: 4, PP: 0, SP: 1
main:003> 
unknown instruction: 145
At IP: 4, PP: 0, SP: 1
main:004> 
unknown instruction: 0
At IP: 4, PP: 0, SP: 1
main:005> 
unknown instruction: 145
At IP: 4, PP: 0, SP: 1
main:006> 
unknown instruction: 0
At IP: 4, PP: 0, SP: 1
main:007> 
unknown instruction: 145
At IP: 4, PP: 0, SP: 1
main:008> 
Exiting REPL

root@imx6sx-pilot:~# arkscript -dddd
ArkScript REPL -- Version 4.0.0 [LICENSE: Mozilla Public License 2.0]
Type "(quit)" to quit.
main:001> ^C
main:001> (+ 1 2)
main:002> 
unknown instruction: 0
At IP: 4, PP: 0, SP: 1
main:003> 
Segmentation fault
```

### Documentation

- [X] I have read existing related documentation before submitting this report
- [X] I have searched for an existing issue before posting

**Comment by SuperFola** [comment]
Hi, thanks for your bug report

Does it work if you create a .ark file with the following content?

```lisp
(let foo "bar")
(print (+ foo "bar"))
```

This should print barbar to the terminal

If this works this might be a REPL issue in v4.0 rather than a target architecture bug

**Comment by hardliner66** [comment]
I just tried it and it seems to work:
```
root@imx6sx-pilot:~# arkscript test.ark 
barbar
```

Edit:
I'm trying to use v3.5.0

**Comment by hardliner66** [comment]
I can confirm that v3.5.0 works perfectly fine on ARMv7.

**Comment by SuperFola** [comment]
A big change occurred in the way instructions are generated between v3.x and v4.0 so I wouldn't be surprised if this broke the REPL, which is often undertested (it relies on the vm state heavily, and plays with the instruction pointer).

I'll look into it tonight

**Comment by SuperFola** [comment]
I can confirm this is a REPL bug, can replicate on dev but not on feat/parser (which adds the new parser and some other stuff ; it's been a while but I might have fixed the REPL bug because I can not focus on a single task at a time haha)

Is it okay if I close the and mark it as solved in the upcoming release?
