### ISSUE TITLE
Mention tool used for diagram in Code Structure section

### ISSUE THREAD

**Issue by lucic71** [ArkScript-lang/Ark#434]
### Is your feature request related to a problem?

I would like to know what is the name of the tool used for creating the diagram in the Code Structure section.

### Describe the solution you would like

If the tool used for creating the svg is open source, I think it would be worth integrating the code for creating the svg into the project.

### Is it a big modification to the language? Leave it if you don't know

- [ ] Breaking change
- [ ] Compiler/syntax modifications
- [ ] Runtime modifications (standard library, modules, packages...)

**Comment by SuperFola** [comment]
Hello, I don't think mentioning the tool nor integrating its code here would be useful as it's already open source and hosted by githubocto, see the CI: https://github.com/ArkScript-lang/Ark/blob/dev/.github/workflows/ci.yml#L53.

**Comment by lucic71** [comment]
Thank you!
