### ISSUE TITLE
Plugin : custom types

### ISSUE THREAD

**Issue by PierrePharel** [ArkScript-lang/Ark#70]
In this moment, I'm working on msgpack module for Ark, and I need an clear and explicit **way for define custom types** for modules (plugin).

**Comment by SuperFola** [comment]
Hi, as said on the discord server I'll try to work on this as soon as possible, you can expect a first version by the end of the week!

I'm really looking forward to seeing what you came up with for the message pack module 😄

**Comment by SuperFola** [comment]
Done in f76727b63007b194d2af96a2552d52e791217826
