### ISSUE TITLE
Question: should we put the modules in another repository?

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#71]
Should we put the modules in another repository?

I'm asking this because the repository will definitely grow a lot with all the modules we are going to add, and when someone wants to start experimenting on a project, often they don't like having to download a bunch of things that they aren't going to use.

Having like a module store would be quite cool, what do you think?

**Comment by Natendrtfm** [comment]
I agree !

**Comment by SuperFola** [comment]
Maybe an ArkScript package manager made in the language once we have a complete support of argument parsing and a working network module (see #74)

**Comment by Natendrtfm** [comment]
The main problem would be the hosting of this manager 
If we want to do the package manager, the modules needs to be hosted somewhere
If a two ideas : 
The modules are all stocked on a website/API to grab with the package manager

Or it uses an API that redirect to the github repo of the module and then it clone/download the repo

The first solution will need more resources and a server on which the modules are hosted m

**Comment by SuperFola** [comment]
> the modules needs to be hosted somewhere

I could easily order a VPS with about 500GB of storage for that, thanks to the prices being very low. What would be induced by doing this would be that we would need a team of reviewers for modules, to avoid "bad" modules (like we can find on NPM sometimes, eg "is this variable a number/bool..."), but that's still doable.

**Comment by Natendrtfm** [comment]
While the language is small it will be doable

We just need some rules for the modules to be accepted

**Comment by SuperFola** [comment]
Has been done in https://github.com/ArkScript-lang/modules
