### ISSUE TITLE
Adding macros

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/Ark#75]
I think we should consider adding macros to the language, since it would have been (imo) very useful for some programs, and also to extend the language (eg if we want to define a `forEach` "keyword", which wouldn't use a function behind but directly copy the code doing the `forEach` thing)

**Comment by sabiha22** [comment]
Can I work on this?

**Comment by SuperFola** [comment]
No problem, we'll just need to discuss what is needed before diving in!

**Comment by sabiha22** [comment]
I am a beginner in Open source. I don't exactly know how to proceed but I am proficient with C++. Can you help me approach this?

**Comment by SuperFola** [comment]
No problem!

We're working through pull requests, thus you have to fork the repository first, then create your branch on your fork (`git checkout -b branch_name`), which you have to clone on your PC.

Then, just make sure to make relevant commit message (eg, `git add src/Compiler/MacroParser.cpp`, then `git commit -m "adding first version of a macro parser"`), and when you are ready, `git push -u origin branch_name`, and make a pull request on this repository, we'll review the code.

(I assumed you know a bit about git, if not, let me know and I can add more details)

------

The goal of having macros in the language would be (imo) to have a basic thing like C++ defines: `#define thing(arg) std::cout << arg;`.

On the syntax side, I don't know yet if it could be directly in comments (if so we should avoid eliminating comments when lexing), like `#(defmacro name arg1 arg2... body)` where `(name arg1 arg2...)` would be replaced by `body` ; or if we should add keyword like `macro` (working exactly like `fun`): `(let name (macro (arg1 arg2...) body))`.

As I am writing this, I think adding a keyword for this could be great.

On the "how should it work" side, macros could be evaluated by the compiler **or** not, then we just do some pattern matching and replace it accurately (I think it's a good solution since I'm planning to add a constant folding algorithm in the compiler). We can assume that a macro is correct (while forbidding nested macros like `(let mac1 (macro (a) (macro (b) ...)))`) if the parser can parse it.

Thus macros would be eliminated after parsing, before compiling.

------

If you need more details, feel free to hit me up or join the discord

**Comment by sabiha22** [comment]
I understand how macros work. But haven't heard about nested macros. Will read it up and get back to you! Thanks a lot.

**Comment by SuperFola** [comment]
About nested macros, that's because (iirc) in some lisp we can define a macro inside another, but here it's more basic, more like the C/C++ preprocessor

**Comment by SuperFola** [comment]
Hi there, just wanted to inform you that we're still discussing the syntax of macros, but it won't change how they work

**Comment by sabiha22** [comment]
Yup, got that. Also, I wanted to ask how do I begin writing the code?

**Comment by SuperFola** [comment]
You mean what to write and where or how to do it with git?

If it's with git, fork the repo and create a new branch (git checkout -b branch_name), and then as said before it's in the lexer/parser.

If that's about where and what, the best thing to start with will be to have a look at the lexer and the parser to understand how it works.

Then to add macros you would need to have a look at the parsing method of the parser (we established the syntax : `!{name (args) body}` and `!{name body}`), thus you would need to add a new kind of token in the lexer : `!{`.

**Comment by sabiha22** [comment]
Oh okay. I will do that. Thanks!

**Comment by SuperFola** [comment]
Hi @sabiha22 !

Just wanted to check on you to know if you still want to work on this / already started to work on this!

**Comment by sabiha22** [comment]
Hey! I do want to work on this but I have back to back exams so I am not able to take out much time for things other than academics. Really sorry :( 
I will start working as soon as I am done with them.

**Comment by SuperFola** [comment]
No problem, I understand!

Good luck with your exams then :)

**Comment by SuperFola** [comment]
Without any news, I'm taking the task

**Comment by sabiha22** [comment]
Hey! Really sorry for this, under a lot of pressure, won't be able to work on this. I apologize for the inconvenience.

**Comment by SuperFola** [comment]
No problem, good luck with school!
